jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/gagechaeum_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
jdbc.username=gage_user
jdbc.password=12341234

cors.allowed-origins=http://localhost:5173,http://localhost:8080

# External APIs
external.gov24.api.url=https://api.odcloud.kr/api/gov24/v3/serviceList
external.gov24.api.serviceKey=2691f153cfff28963c77e6c071eaa7413a03e71bcd646516a13005755fbd63c5
